MKDIR=mkdir -pv
RM=rm -rf
DEBUG_BUILD_OUTPUT_DIR=debug
RELEASE_BUILD_OUTPUT_DIR=release
UNIT_TEST_BUILD_OUTPUT_DIR=unit_test

ifeq ($(VARIANT), DEBUG)
  BUILD_OUTPUT_DIR = $(DEBUG_BUILD_OUTPUT_DIR)
endif
ifeq ($(VARIANT), RELEASE)
  BUILD_OUTPUT_DIR = $(RELEASE_BUILD_OUTPUT_DIR)
endif
ifeq ($(VARIANT), UNIT_TEST)
  BUILD_OUTPUT_DIR = $(UNIT_TEST_BUILD_OUTPUT_DIR)
endif

OBJ_DIR = $(BUILD_OUTPUT_DIR)/obj

PROD_LIB = $(OBJ_DIR)/prod.a

# 'PROD_OBJ' will be added to by module makefiles
PROD_OBJ = 

.PHONY : all clean
all : $(VARIANT)
	@echo Done building variant $(VARIANT)

clean :
	@echo Cleaning everything
	$(RM) $(DEBUG_BUILD_OUTPUT_DIR) $(RELEASE_BUILD_OUTPUT_DIR) $(UNIT_TEST_BUILD_OUTPUT_DIR)

$(PROD_LIB) : $(BUILD_OUTPUT_DIR) $(OBJ_DIR) $(PROD_OBJ)
	touch $(PROD_LIB)

$(OBJ_DIR) :
	@$(MKDIR) $(OBJ_DIR)

DEBUG : $(BUILD_OUTPUT_DIR) $(PROD_LIB)
	@echo Nothing specified for variant DEBUG

RELEASE : $(BUILD_OUTPUT_DIR) $(PROD_LIB)
	@echo Nothing specified for variant RELEASE
	
UNIT_TEST : $(BUILD_OUTPUT_DIR) $(PROD_LIB)
	@echo Nothing specified for variant UNIT_TEST

$(UNIT_TEST_BUILD_OUTPUT_DIR) :
	@$(MKDIR) $(UNIT_TEST_BUILD_OUTPUT_DIR)

$(DEBUG_BUILD_OUTPUT_DIR) :
	@$(MKDIR) $(DEBUG_BUILD_OUTPUT_DIR)

$(RELEASE_BUILD_OUTPUT_DIR) :
	@$(MKDIR) $(RELEASE_BUILD_OUTPUT_DIR)
